### ISSUE TITLE
Unknow Task ui5-task-nwabap-deployer

### ISSUE THREAD

**Issue by michal-majer** [pfefferf/ui5-nwabap-deployer#1]
Hey,

I am receiving an error during build:

```
info builder:builder Building project ProjectName not including dependencies...
info builder:builder 🛠  (1/1) Building project ProjectName
ERR! builder:builder Build failed in 3.93 ms
info builder:builder Executing cleanup tasks...

⚠️  Process Failed With Error

Error Message:
taskRepository: Unknown Task ui5-task-nwabap-deployer
```
Any tips? :)

**Comment by pfefferf** [comment]
Have you defined the dependency in your package.json? Can you show the file content?

**Comment by xavierguiguen** [comment]
Got the same issue, solved it by adding this at the end of ui5.yml:

```
---
specVersion: '1.0'
kind: extension
metadata:
  name: ui5-task-nwabap-deployer
type: task
task: 
  path: node_modules/ui5-task-nwabap-deployer/lib/ui5-task-nwabap-deployer.js
```

**Comment by michal-majer** [comment]
@xavierguiguen Thanks it works now :)

**Comment by pfefferf** [comment]
@xavierguiguen: But that is not the intended solution. Did you add the 
`"ui5": {
  "dependencies": [
     "ui5-task-nwabap-deployer"
  ]
}`
configuration in your package.json?

**Comment by xavierguiguen** [comment]
@pfefferf yes I did it too but that was not enough to solve the isssue

**Comment by pfefferf** [comment]
@xavierguiguen: Ok, thanks. Found the error. In the published NPM package, the ui5.yaml file describing the task was missing. I fixed that. Version 1.0.1 is published.
