### ISSUE TITLE
Throw error when connection or credentials not specified

### ISSUE THREAD

**Issue by marcelschork** [pfefferf/ui5-nwabap-deployer#14]
Hi Florian,
thanks for implementing this cool custom UI5 task. We use it in a CI/CD scenario and it would be cool if our deployment step would fail in following situations:
 - no connection specified
 - credentials missing

At the moment it's only logged to STDERR, but for the build task everything seems fine despite that the app is not successfully uploaded.

Best regards,
Marcel

**Comment by pfefferf** [comment]
Fixed with ui5-task-nwabap-deployer@**1.0.12**
