### ISSUE TITLE
ui5-task-nwabap-deployer has problems with https://github.com/pwasem/ui5-shim-babel-polyfill

### ISSUE THREAD

**Issue by DerGuteWolf** [pfefferf/ui5-nwabap-deployer#16]
We have transpile for task and middleware in our ui5 build.
To also have the required babel runtime we use https://github.com/pwasem/ui5-shim-babel-polyfill exactly as described in the README there.
For ui5 serve this works, the two files added to the manifest are served and the app runs.
When using ui5 build --all the files from this babel runtime are in dist/resource, however they are NOT deployed by ui5-task-nwabap-deployer. Thus the deployed app does not find these two files and thus dooes not run.

**Comment by pfefferf** [comment]
This UI5 task (as hopefully every other UI5 task) does not consider what is stored in the file system destination. It takes the data from the UI5 tooling provided workspace which is written to the file system at the end of a build.

If that task you use does not use the workspace or is executed not before the deploy task, then the files cannot be considered.

**Comment by DerGuteWolf** [comment]
Hi @pfefferf ,
thanks for the quick response.
This is NOT another task but a dependency which is build way before the deploy task by the --all option. The deploy task is the last task executed.
I know well of the virtual file system used in the whole build, the reference to the dist directory was just to assure that the files are indeed created in the course of the build.
And this a dependency and not a dev dependency.
It seems that the build makes a difference between files in the workspace and files from dependencies. Eg a middleware live serve serves both, however a build task seems not necessarily to deal with files from dependencies.

I have also created https://github.com/pwasem/ui5-shim-babel-polyfill/issues/1 .
