### ISSUE TITLE
Please add the option to also deploy files from dependencies

### ISSUE THREAD

**Issue by DerGuteWolf** [pfefferf/ui5-nwabap-deployer#17]
See https://github.com/pfefferf/ui5-nwabap-deployer/issues/16, https://openui5.slack.com/archives/C0A7QFN6B/p1590570444152800 and https://github.com/SAP/ui5-builder/issues/204#issuecomment-508032943 .

I would propose adding an option resourcesFromDependencies also with a glob pattern and then not only using workspace.byGlob(sResourcePattern) in https://github.com/pfefferf/ui5-nwabap-deployer/blob/master/packages/ui5-task-nwabap-deployer/lib/ui5-task-nwabap-deployer.js#L63 but also dependencies.byGlob(sResourceFromDependenciesPattern) if this option was provided.

**Comment by pfefferf** [comment]
From my point of view this proposal is an ugly workaround for the current build behaviour. Therefore I do not really want to integrate that; especially with a view on the ongoing dicussions for enhancing the build with the option to integrate dependencies.
For the moment you can use the approach described with the "copy-shims" task, which needs to be executed before the deploy task.
