### ISSUE TITLE
How to skip files which are already there in SAP BSP Application

### ISSUE THREAD

**Issue by rajk595** [pfefferf/ui5-nwabap-deployer#21]
Hi Team,

I have an requirement where while uploading files via this module I want to skip files which are already there in SAP BSP Application.

For example i already have a file in SAP system webcontent/configuration.js

By using this module how can I skip this file while uploading I tried using negate option while providing src but it's trying to delete the file rather skipping

**Comment by pfefferf** [comment]
The current behavior is, that files are sync. Meaning, if you are excluding files, they are removed from the BSP container.
There are no plans to support your scenario.
