### ISSUE TITLE
No transport found attached to the user during upload in abap repository

### ISSUE THREAD

**Issue by maximnofate** [pfefferf/ui5-nwabap-deployer#31]
Hi!
i'm trying to deploy ui5 app with grunt, using nwabap-ui5uploader.
I want to upload app in transport, attached curent user, but i got error in console:
![error](https://user-images.githubusercontent.com/24478261/99044199-6f770c00-25a0-11eb-8122-b1bc998a0093.jpg)
I wanted to know why it might be ...
Could this be because I did not initially create this request, and only then I changed the owner of the request to myself? Although it would be logical for apap-uploader to pick up the request (since it works in sap webide fullstack)

**Comment by pfefferf** [comment]
Can you show your config?

**Comment by maximnofate** [comment]
yes, sorry, I forgot
![config](https://user-images.githubusercontent.com/24478261/99045879-0ba21280-25a3-11eb-8aeb-38795d931848.JPG)

**Comment by pfefferf** [comment]
Tested it on my local environment:
- Create workbench transport with different user (compared to deployment user).
- Reassign transport to deployment user.
- Deployment -> transport is found.

So I think there is some little piece "wrong" in your setup.

**Comment by maximnofate** [comment]
means the set of options in nwabap_ui5uploader is correct?
The config just crashes on this task...
this my gruntfile:
https://gist.github.com/vrnnofate/64566508de857b186f212efd890f5d64

**Comment by pfefferf** [comment]
config is ok
