### ISSUE TITLE
Error: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Fjaoos** [pfefferf/ui5-nwabap-deployer#34]
Hi,

I am trying to establish a CI pipeline with jenkins in AWS, WebIDE and Bitbucket.

Unfortunately the deployment process fails and I cannot determine the fault.
Here is my error text: 
![image](https://user-images.githubusercontent.com/19299859/111621391-3a95f280-87e8-11eb-938c-a16443f612bd.png)

This is my ui5.yaml:
![image](https://user-images.githubusercontent.com/19299859/111621545-67e2a080-87e8-11eb-8909-0a71a2a75f12.png)

Regards
Nils

**Comment by pfefferf** [comment]
Have you any JSON file with a circular reference in your project? 
Are you able to share your project?

**Comment by Fjaoos** [comment]
Hi, 
the deployment works to a different SAP machine. I think it has to do with systems that cannot be reached. 

The project does not have any circular reference. I think it is coming from the error object.
