### ISSUE TITLE
Empty transport requests created

### ISSUE THREAD

**Issue by sivajankumaran** [pfefferf/ui5-nwabap-deployer#36]
Hi,

I have a BSP application locked on a open transport. When I specify createTransport:true and transportUseLocked:true what happens is that the application is deployed correctly on the existing transport however an empty new transport request is created each time. Is this the intended functionality? I hoped the new transport would only be created if a transport was not found with the BSP package. As I use this as part of a CI build pipeline, I'm ending up with a lot of empty transports being created.

Thanks
Sivajan

**Comment by pfefferf** [comment]
@sivajankumaran Thx for bringing that up. Issue is resolved and available with ui5-nwabap-deployer-core@1.0.14. Just update your npm dependencies.

**Comment by sivajankumaran** [comment]
Thanks a lot for fixing it so quickly. Appreciate it.
