### ISSUE TITLE
Property useStrictSSL

### ISSUE THREAD

**Issue by CarlosOrozco88** [pfefferf/ui5-nwabap-deployer#37]
Hi!
I think i found a bug in:
https://github.com/pfefferf/ui5-nwabap-deployer/blob/237750fa7003c43930fa0bc54fde6b4b7119238d/packages/ui5-nwabap-deployer-core/lib/AdtClient.js#L108

I think this line:
```
rejectUnauthorized: that._oOptions.useStrictSSL
```
should look like this:
```
rejectUnauthorized: that._oOptions.conn.useStrictSSL
```
Or this is intentional? I am facing problems with SSL certificates in secure connections...

Thanks!

**Comment by pfefferf** [comment]
Thx for bringing that up. Fixed with ui5-nwabap-deployer-core@1.0.15
