### ISSUE TITLE
[ui5-task-nwabap-deployer] Don't use fixed Env-Variables as only option

### ISSUE THREAD

**Issue by Kyrodan** [pfefferf/ui5-nwabap-deployer#40]
There are several *fixed/pre-defined* environment variables that can be used if the value is *not* specified in YAML file.
I would suggest to also have a "special" value inside the YAML file, that points to a defined Environment Variable.
This special value should be the same, like it is used in @sap/ux-ui5-tooling: "env:MY_OWN_VAR".

I may create a PR if you accept this feature request.

**Comment by pfefferf** [comment]
Don't see a real value in that addition.

**Comment by Kyrodan** [comment]
The value would be: 
* works the same as official fiori tooling (which is not really usable for deployment as of several issues at the moment)
* we have a working CI-Build with a *different* variable name for Username and Password "injected" in our CI-Environment. So an additional task is required to "copy" the variables. We have a huge Fiori-Code-base with approx 30 Apps and 10 Libs.
* fixed values always lead to requests like mine :-)
