### ISSUE TITLE
Not able to deploy the ui5 project to SAP ABAP server

### ISSUE THREAD

**Issue by saketamraotkar13** [pfefferf/ui5-nwabap-deployer#43]
Hi,

We are developing the ui5 project using yomen generator (easy ui5) and trying to deploy the app using npm run deploy but it did not deploy the app and gives the error "Error: Operation Existing Transport Determination for BSP Container: Expected status code 200, actual status code 403".

After investigation we came to know that issue is at the line no. 80:
fnCallback(new Error(`Operation Existing Transport Determination: Expected status code ${fsutil.HTTPSTAT.ok}, actual status code ${oResponse.statusCode}`));
it is not passing the credentials and coming back with mentioned error.

Please help us to resolve the issue.

Regards
Saket A

**Comment by pfefferf** [comment]
Credentials are set in the AdtClient object instance when created. They do not have to be passed again at that point.

Maybe you want to share your configuration and describe what your are using (grunt, ui5 tooling task, cli).

**Comment by saketamraotkar13** [comment]
After creation of project, we are trying to deploy the project to SAP NW ABAP server, we follow below steps:
1.  we navigate to ui5.yaml and updated the information as below:
--------
server:
  customMiddleware:
    - name: ui5-middleware-livereload
      afterMiddleware: compression
      configuration:
        port: 35729
        path: uimodule/webapp
    - name: ui5-middleware-route-proxy
      afterMiddleware: compression
      configuration:
        debug: false
        /sap/opu/odata/sap/:
          target: http://sapandbox:4111
          auth:
            fromEnv: false
            user: XYZ
            pass: ****
builder:
  customTasks:
  - name: ui5-task-nwabap-deployer
    afterTask: generateVersionInfo
    configuration:
      resources:
        path: dist/uimodule
        pattern: "**/*.*"
      connection:
        server: http://sapandbox:4111
      authentication:
        user: XYZ
        password: ****
      ui5:
        language: EN
        package: $TMP
        bspContainer: zzyomen1
        bspContainerText: Generated with easy-ui5
        transportNo: ""
        calculateApplicationIndex: true
---------------------------------------------------------
after making changes, we are running npm run deploy command from project directory.

**Comment by pfefferf** [comment]
Config looks ok (beside the fact that no property `resources.path` exists, but that is not an issue for the appearing error). I tested it with the latest versions on my local environment and everything works fine. So I guess your used user has not enough privileges.

**Comment by saketamraotkar13** [comment]
issue resolved, we activate the ADT service on ABAP server and tried deploying it, it deployed the app.
