### ISSUE TITLE
Ressource unchanged after successful build and deploy

### ISSUE THREAD

**Issue by Fjaoos** [pfefferf/ui5-nwabap-deployer#44]
Hi,

I tried to deploy a change in one App, for testing purposes, from a jenkins server and from my local machine.
Although all checks are passed and a successfull build and deploy to the system, the ressources on that system remain unchanged, the app acts as before and no transport is created or updated.
We are using a certain user for the deployment though. 
This is the ui5.yaml:
![image](https://user-images.githubusercontent.com/19299859/121506205-cc765b80-c9e3-11eb-89ed-ef00f230c0ff.png)
No error in st22 and the Transport is not updated either.
Here's the build log:
`PS C:\Git\gkvuipatestd> ui5 build
INFO: Using local @ui5/cli installation

info builder:builder Building project gkvuipatestd not including dependencies...
info builder:builder 🛠   (1/1) Building project gkvuipatestd
info builder:builder application gkvuipatestd 🔨 (1/9) Running task escapeNonAsciiCharacters...
info builder:builder application gkvuipatestd 🔨 (2/9) Running task replaceCopyright...
info builder:builder application gkvuipatestd 🔨 (3/9) Running task replaceVersion...
info builder:builder application gkvuipatestd 🔨 (4/9) Running task generateFlexChangesBundle...
info builder:builder application gkvuipatestd 🔨 (5/9) Running task generateComponentPreload...
info builder:builder application gkvuipatestd 🔨 (6/9) Running task createDebugFiles...
info builder:builder application gkvuipatestd 🔨 (7/9) Running task uglify...
info builder:builder application gkvuipatestd 🔨 (8/9) Running task generateVersionInfo...
info builder:builder application gkvuipatestd 🔨 (9/9) Running task upload0...
info builder:customtask:nwabap-deployer file /manifest-bundle.zip: deleted.9/9) Running task upload0...
info builder:customtask:nwabap-deployer file /sap-ui-cachebuster-info.json: deleted.ing task upload0...
info builder:customtask:nwabap-deployer file /resources/gkv/uipa00/gkvuipatestd/di.code-validation.core_issues.json: deleted.
info builder:customtask:nwabap-deployer file /resources/gkv/uipa00/gkvuipatestd/neo-app.json: deleted..
info builder:customtask:nwabap-deployer file /resources/gkv/uipa00/gkvuipatestd/resources.json: deleted.
info builder:customtask:nwabap-deployer folder /resources/gkv/uipa00/gkvuipatestd: deleted.k upload0...
info builder:customtask:nwabap-deployer folder /resources/gkv/uipa00: deleted.) Running task upload0...
info builder:customtask:nwabap-deployer folder /resources/gkv: deleted.🔨 (9/9) Running task upload0...
info builder:customtask:nwabap-deployer file /Component-dbg.js: no change detectednning task upload0...
info builder:customtask:nwabap-deployer file /Component-preload.js: updated./9) Running task upload0...
info builder:customtask:nwabap-deployer file /Component.js: no change detected) Running task upload0...
info builder:customtask:nwabap-deployer file /control/XmlInputTreeItem-dbg.js: no change detectedad0...
info builder:customtask:nwabap-deployer file /control/XmlInputTreeItem.js: no change detectedupload0...
info builder:customtask:nwabap-deployer file /controller/Main-dbg.controller.js: updated.ask upload0...
info builder:customtask:nwabap-deployer file /controller/Main.controller.js: updated.ng task upload0...
info builder:customtask:nwabap-deployer file /css/style.css: no change detected Running task upload0...
info builder:customtask:nwabap-deployer file /i18n/i18n.properties: no change detectedg task upload0...
info builder:customtask:nwabap-deployer file /index.html: no change detected/9) Running task upload0...
info builder:customtask:nwabap-deployer file /localService/YGKV_PAOO_C_SPRO_RDS_ANNO_MDL.xml: no change detected
info builder:customtask:nwabap-deployer file /localService/metadata.xml: no change detectedk upload0...
info builder:customtask:nwabap-deployer file /localService/mockdata/ProcessSet.json: no change detected
info builder:customtask:nwabap-deployer file /localService/mockserver-dbg.js: no change detectedoad0...
info builder:customtask:nwabap-deployer file /localService/mockserver.js: no change detected upload0...
info builder:customtask:nwabap-deployer file /manifest.json: no change detected Running task upload0...
info builder:customtask:nwabap-deployer file /model/models-dbg.js: no change detectedng task upload0...
info builder:customtask:nwabap-deployer file /model/models.js: no change detectedunning task upload0...
info builder:customtask:nwabap-deployer file /model/util/Converter-dbg.js: no change detectedupload0...
info builder:customtask:nwabap-deployer file /model/util/Converter.js: no change detectedask upload0...
info builder:customtask:nwabap-deployer file /model/util/Formatter-dbg.js: no change detectedupload0...
info builder:customtask:nwabap-deployer file /model/util/Formatter.js: no change detectedask upload0...
info builder:customtask:nwabap-deployer file /resources/sap-ui-version.json: updated.ng task upload0...
info builder:customtask:nwabap-deployer file /test/integration/navigationJourney-dbg.js: no change detected
info builder:customtask:nwabap-deployer file /test/integration/navigationJourney.js: no change detected
info builder:customtask:nwabap-deployer file /test/integration/opaTests.qunit.html: no change detected.
info builder:customtask:nwabap-deployer file /test/integration/pages/Main-dbg.js: no change detected...
info builder:customtask:nwabap-deployer file /test/integration/pages/Main.js: no change detectedoad0...
info builder:customtask:nwabap-deployer file /test/mockserver.html: no change detectedg task upload0...
info builder:customtask:nwabap-deployer file /test/unit/model/models-dbg.js: no change detectedload0...
info builder:customtask:nwabap-deployer file /test/unit/model/models.js: no change detectedk upload0...
info builder:customtask:nwabap-deployer file /test/unit/model/util/Converter-dbg.js: no change detected
info builder:customtask:nwabap-deployer file /test/unit/model/util/Converter.js: no change detected0...
info builder:customtask:nwabap-deployer file /test/unit/model/util/Formatter-dbg.js: no change detected
info builder:customtask:nwabap-deployer file /test/unit/model/util/Formatter.js: no change detected0...
info builder:customtask:nwabap-deployer file /test/unit/types/XmlType-dbg.js: no change detectedoad0...
info builder:customtask:nwabap-deployer file /test/unit/types/XmlType.js: no change detected upload0...
info builder:customtask:nwabap-deployer file /test/unit/unitTest.qunit.html: no change detectedload0...
info builder:customtask:nwabap-deployer file /types/XmlType-dbg.js: no change detectedg task upload0...
info builder:customtask:nwabap-deployer file /types/XmlType.js: no change detectednning task upload0...
info builder:customtask:nwabap-deployer file /view/ATDATable.fragment.xml: no change detectedupload0...
info builder:customtask:nwabap-deployer file /view/Add.fragment.xml: no change detected task upload0...
info builder:customtask:nwabap-deployer file /view/Main.view.xml: updated.(9/9) Running task upload0...
info builder:builder Build succeeded in 21 s
info builder:builder Executing cleanup tasks...`

**Comment by pfefferf** [comment]
Are the files - which are marked as deleted - still available in the BSP Container?
What entries are in your transport request; no entries, only the bsp container or single file entries (options 2 and 3 only if the transport was already used for e.g. previous deployments)?

**Comment by Fjaoos** [comment]
Some are and some aren't:
![image](https://user-images.githubusercontent.com/19299859/121512910-88d32000-c9ea-11eb-98e7-64b44cd0ab8b.png)
There is not any entry for that user for that specified transport request either.

**Comment by pfefferf** [comment]
Have not seen such a behavior so far. And without your example it is hard for me to analyze. Do you have any chance to debug the code and check the response codes of the requests to the backend system?

It would also be interesting if the behavior can be reproduced if you drop the bsp container from the backend system, make a fresh deploy and deploy again (with some changes).

**Comment by Fjaoos** [comment]
To be honest: I am completely new to node.js and VS Code but I somehow managed to start a debugging session.
It appears that my requests do return a 403 forbidden.
![image](https://user-images.githubusercontent.com/19299859/121518157-72c85e00-c9f0-11eb-9bbb-db5e3366fd6f.png)

However there is a typo in the constant structure that prevents the proper handling of those responses:
![image](https://user-images.githubusercontent.com/19299859/121518091-6217e800-c9f0-11eb-884a-400bcb8a9919.png)
FileStore.util:
![image](https://user-images.githubusercontent.com/19299859/121518325-a60aed00-c9f0-11eb-8b1a-a9e097a43790.png)

Please do not fix this! I want to try a pull request for the first time.

**Comment by pfefferf** [comment]
Is your user authorized to modify the bsp container?

Nevertheless there is an issue in the deployer coding. In FileStore.util "bad_rquest" must be called "bad_request" (stupid typo). With that correction you should get a valid error message instead of the logs that the files are processed. I will provide a fix for that.

For test reasons you can correct the typo temporary in your local environment to get the error message. But you have to check the authorizations of your user.

**Comment by Fjaoos** [comment]
I got the proper error result after I fixed the typo.

Would you be so kind and let me fix that typo? I want to try to contribute to projects for once.

**Comment by pfefferf** [comment]
Sure, you can make a PR for that. Thx

**Comment by Fjaoos** [comment]
Thank, you. I hope I have done it the right way.

**Comment by pfefferf** [comment]
Thx, v1.0.23 of ui5-nwabap-deployer-core package is released now.
