### ISSUE TITLE
Option useStrictSSL doesn't work as expected

### ISSUE THREAD

**Issue by jeremies** [pfefferf/ui5-nwabap-deployer#46]
In the new version of  ui5-nwabap-deployer-core that uses axios, I can't deploy to a Gateway that has an invalid SSL certificate, even If I have the option useStrictSSL set to false. To deploy, now, I am using an old version of grunt-nwabap-ui5uploader.

I think that this can't be solved in a clean way because it's a bug of axios. https://github.com/axios/axios/issues/535

Maybe axios can be replaced but I think that is not easy.

If I put process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'; in the code, it works. But I think that this is not the best way to go.

I have debugged the code and found that the following line [line 130 AdtClient.js](https://github.com/pfefferf/ui5-nwabap-deployer/blob/bc602d7c184f8787ea9cc71412dd996c05860fee/packages/ui5-nwabap-deployer-core/lib/AdtClient.js#L130) is not enough for invalid SSL certificates.

**Comment by pfefferf** [comment]
The implemented approach deals with self-signed certificates (as described in the axios issue).
Axios will not be replaced.
To go ahead, you can adapt your script and set the NODE_TLS_REJECT_UNAUTHORIZED env var.
