### ISSUE TITLE
"Connection error has occurred" - how to analyze further?!

### ISSUE THREAD

**Issue by treee111** [pfefferf/ui5-nwabap-deployer#49]
Hi!

first: Great tool / npm-package that you created - I especially like the fast responses here in the issues 👍 

We want to use your "ui5-nwabap-deployer-cli" UI5 Deployer together with our CI/CD Pipeline in AWS.
We are running an AWS deployment agent on the OS of our Gateway development Systems.

When the Pipeline is successful, it triggers the deployment agent . Then, on the OS, this script is running:
![image](https://user-images.githubusercontent.com/53038537/123075170-452fdb80-d418-11eb-9ab2-59f36ce3e2dd.png)

**Now to the "question":**
We have two nearly identical development-systems.
On one of them it works flawless, on the other it doesn't:
1. sandbox development system:
- v1.x.x works with HTTP Gateway URL
- v1.x.x works with HTTPS Gateway URL
- v2.1.0 works with HTTPS Gateway URL
2. development system:
- HTTP is not enabled
- v1.x.x does not work with HTTPS Gateway URL
- v2.1.0 does not work with HTTPS Gateway URL

Both times, we get the same error after the `ui5-deployer deploy` command: "Connection error has occurred; retry attempt x":
![image](https://user-images.githubusercontent.com/53038537/123072957-48c26300-d416-11eb-9e21-ce98e12cdb55.png)

We investigated and viewed a lot of logs but can not figure out the difference between both systems or what might be the difference on OS level.

Do you have any tip how we could proceed any further to circumscribe the cause for that and what needs to be changed in our setup?

Many thanks in advance!

This is our `.ui5deployrc` file:
![image](https://user-images.githubusercontent.com/53038537/123073975-3563c780-d417-11eb-8d68-bde4188c70f8.png)

**Comment by pfefferf** [comment]
Hi,

normally when that error occurs either the server URL (incl. port) is wrong, the URL cannot be reached (because e.g. of some proxy settings) or the respective service is not activated. 
I think as you are using the 2.x.x version, you have activated the OData Service /UI5/ABAP_REPOSITORY_SRV already on your second system too.?

**Comment by treee111** [comment]
Hi,

yes, I activated the OData Service /UI5/ABAP_REPOSITORY_SRV on both systems and deactivated virus scanning like you mentioned in the two notes.
Somehow there is a problem before entering SAP I think because in SM21 we do not get any error logged.

Are there any SICF services other than the adt which need to be activated as well?

**Comment by pfefferf** [comment]
Beside the ABAP Repo Service only the ADT endpoints for transports (/sap/bc/adt/cts/transports) and transportChecks (/sap/bc/adt/cts/transportchecks) are used. If you have ADT services enabled that should be fine.

Have to tried in your pipeline to call the ping service of your development system using a simple ping; to ensure that it can be reached in general?

**Comment by treee111** [comment]
Thank you for the hint - in my opinion that doesn't look bad but I gonna discuss that with SAP Basis once again:
![image](https://user-images.githubusercontent.com/53038537/123084516-8082d800-d421-11eb-9b67-c0c789cd0ff1.png)

I gonna give a update here, if we resolved it and the deployment is running.

**Comment by treee111** [comment]
a Infrastructure Colleague made a change to the AWS deployment agent and we are one step further:
![image](https://user-images.githubusercontent.com/53038537/123215826-305f5080-d4c9-11eb-8649-facc94ea46be.png)

I compared SICF nodes, logon procedures among the "adt", "adt/transports", "ABAP_REPOSITORY_SRV" and the base SICF nodes.
I think the problem is somewhere in the region of authorization?!

Do you have an idea what could cause the error in the Screenshot?

**Comment by pfefferf** [comment]
Does the user on the system have enough rights (aka development rights)?

**Comment by treee111** [comment]
Yes, if i run ./ui5-deployer local in VSCode with the Deployment User & Password it is succesful and deploys to the Gateway.

**Comment by treee111** [comment]
during further analysis I found out that the error message "Operation Existing Transport Determination..." is issues in two lines.
That makes it not easy to distinguish where the error message really comes from.
In our case, I think it's line 159 and has to do something with the CSRF Token (Handling)

Do you think it makes sense to distinguish the following two error-messages?

https://github.com/pfefferf/ui5-nwabap-deployer/blob/97b33d7236147a23ba0265be141532a82b0f7877/packages/ui5-nwabap-deployer-core/lib/TransportManager.js#L93
https://github.com/pfefferf/ui5-nwabap-deployer/blob/97b33d7236147a23ba0265be141532a82b0f7877/packages/ui5-nwabap-deployer-core/lib/TransportManager.js#L159

**Comment by pfefferf** [comment]
The messages are different. The second one contains in additions "... for BSP Container ...". And that is the difference.

**Comment by treee111** [comment]
The issue is not really related to the SAP-side of our "development system".
The root cause our issue is the CSRF token handling or any sort of network-issue on the Linux OS level of the "development system". The Linux OS can not call the URL of the gateway system in a valid way. We checked the use of CSRF token using Postman.

We now use a hack and call the URL of the "development system" from the deployment agent which runs on the "sandbox development system". That works as usually without any problems!

It works now flawless and we have to figure out the issue on our side with infrastucture guys. I close the issue.

@pfefferf - thank you very much for your help in analyzing the issue!!!
