### ISSUE TITLE
nwabap-deployer: unable to get local issuer certificate

### ISSUE THREAD

**Issue by yramamurthy** [pfefferf/ui5-nwabap-deployer#5]
How do I resolve this issue?

**Comment by pfefferf** [comment]
Maybe instead of just posting an error, you want to add some more details like your setup, when the message occurs ...

**Comment by pfefferf** [comment]
no more feedback -> closed

**Comment by yramamurthy** [comment]
I was able to overcome the error by setting the useStrictSSL flag to false in the ui5.yaml configuration file. Thank you!
