### ISSUE TITLE
Documentation: resource->path

### ISSUE THREAD

**Issue by unlogik** [pfefferf/ui5-nwabap-deployer#53]
Hi Florian,

I wanted do define path from where the source files would be collected and couldn't find it in the documentation(readme file). Then I saw path parameter under resource section in comments of the SCP [blog](https://blogs.sap.com/2019/11/24/ui5-tooling-custom-task-to-deploy-ui5-sources-to-an-abap-server/). 
Parameter "path" I saw on this [image.](https://blogs.sap.com/wp-content/uploads/2019/11/ui5-yaml.png)
[ui5.yaml]
`builder:
  customTasks:
  - name: ui5-task-nwabap-deployer
    afterTask: generateVersionInfo
    configuration: 
      resources:
        **path: dist**
        pattern: "**/*.*"`

My suggestion would be to add it to the readme file of this project.

Regards, Dalibor

**Comment by pfefferf** [comment]
The custom task does not have such a configuration option and therefore is not documented of course.

**Comment by unlogik** [comment]
Sorry for asking, but how to define the source folder then?

**Comment by pfefferf** [comment]
Like described in the documentation for the UI5 Tooling (check the standard configuration option for the resources -> configuration -> paths; https://sap.github.io/ui5-tooling/pages/Configuration/)
