### ISSUE TITLE
No error for unlocked resources and invalid transport

### ISSUE THREAD

**Issue by Fjaoos** [pfefferf/ui5-nwabap-deployer#54]
Hi,

I am very sorry to bother you again but I expected the plugin to report an error, if the resources of the application have not been locked on a transport already while create_transport = false and transport_use_user_match= false.

https://github.com/pfefferf/ui5-nwabap-deployer/blob/20c6be93d4385c4d9a626573e6ccaa235d0729f5/packages/ui5-nwabap-deployer-core/lib/ui5-nwabap-deployer-core.js#L299

In my use case, the developer has to specify a certain transport from the system and the transports cannot be created by the plugin.

I think this might be because of "&& oOptionsAdapted.conn.testMode !== true". If this code would be added to the following if and elseif, my case would be working.

Thanks in advance
fjaoos

**Comment by pfefferf** [comment]
Please explain it more clearly: Expecting an error, wehn resources are not locked on a transport? Somehow not clear to me why that should be.

**Comment by Fjaoos** [comment]
Let's say that I want to deploy an application to a system which does not have any unreleased transports and with create_transport = false. In this scenario the resources of the application would not be locked on any open transport but the plugin is not allowed to create a transport for the resources.

**Comment by pfefferf** [comment]
Thx for the explanation. Got it.
My inital thoughts on "disabling" the "create transport" option in test mode - and all related checks - was some kind of "not though enough" :-)

Fixed with v2.2.2 in the core package.

**Comment by Fjaoos** [comment]
Thank you! I like the Dummy Transport :)

**Comment by Fjaoos** [comment]
Thank you for the fix but what happens, with these conditions:
- running in Testmode
- transportUseUserMatch = false
- createTransport = false
- transportUseLocked = false
- oOptionsAdapted.ui5.transportno = COTK910152
- sExistingTransportNo = undefined (Because there is no available transport on the system for the ressources yet)

This leads to a successful build run although it should say: The given transport is not available on the system, the resources are not locked on any transport and the creation of a new transport is not allowed. The resources cannot be deployed

**Comment by pfefferf** [comment]
This will not be checked by the backend service. So it will not be reported. If you have an issue with that, please open an incident for SAP.

**Comment by Fjaoos** [comment]
Thanks, I will do that.
