### ISSUE TITLE
zip contains only files no folders

### ISSUE THREAD

**Issue by silkearians** [pfefferf/ui5-nwabap-deployer#56]
Dear Florian,

when building the zip before the deploy to ABAP with OData service currently only the files are added to the zip but not the folders:
https://github.com/pfefferf/ui5-nwabap-deployer/blob/master/packages/ui5-nwabap-deployer-core/lib/UI5ABAPRepoClient.js#L82
This causes issues in the deployment as the OData service tries to delete the missing folder but fails as there are still files in it. We just received a customer ticket about that.
Would be great if you could also add the folders to the zip and provide new version of ui5-task-nwabap-deployer.

Many thanks in advance and best regards
Matthias & Silke

**Comment by pfefferf** [comment]
Hi,

can you please share more details, cause it is not really clear to my why specific folders should be added? 
Especially, the sentence "tries to delete the missing folder but fails as there are still files in it" is not clear to my. Why a folder should be deployed if it contains no files?
In general all affected files including path (folder paths) are included, if something is not there anymore it should be dropped.

Regards,
Florian

**Comment by silkearians** [comment]
Hi Florian,

we only got the log file so far from the customer and from that it seemed that only the files of a folder were in the zip but not the folder itsself. In that case the OData service detects that the folder should be deleted (which should not be the case and does not work as the folder still contains files). We asked the customer to send us the complete project so that we can further analyze.

Best regards
Matthias & Silke

**Comment by pfefferf** [comment]
Ok, waiting for the log, because at the moment I do not see the issue :-)

**Comment by Fjaoos** [comment]
Hi @pfefferf,

sorry to bother you again but I opened a ticket because the actual deployment shows an error although the test mode run is a success. 

As far as I know the deployment works absolutely fine, if I remove the resources from the system (aka delete the application) and try the deployment again.
My primary concern right now is not the deployment error but the different responses the different modes of the service respond with.

**Comment by pfefferf** [comment]
@Fjaoos Would be great if you could share more details, e.g. your project, the error and the steps you are doing to reproduce the issue.

**Comment by Fjaoos** [comment]
Sure thing but I have to be careful what I can share.
This is the folder structure in the dist folder:
![image](https://user-images.githubusercontent.com/19299859/130247380-55252dbd-e822-439e-ae78-be9164d6a693.png)
And this is the folder structure on the system:
![image](https://user-images.githubusercontent.com/19299859/130247596-c760236f-7a6d-4c19-a478-144f54ef35cf.png)

For some reason the system cannot delete the type folder: 
![image](https://user-images.githubusercontent.com/19299859/130247787-00d03d13-1394-4a04-969b-92f9925ac770.png)

**Comment by pfefferf** [comment]
So you have the local "types" folder with no sub-folder (on server side too), but the service reports with testMode = false, that the "types" folder has a sub-folder which cannot be removed? And with testMode = true you do not get the error?

**Comment by Fjaoos** [comment]
Yes, the test run shows me a success and this log: 
![image](https://user-images.githubusercontent.com/19299859/130248993-36fde23d-8662-46dd-a7fa-f7cca9dc7988.png)

This means that I do not see anything wrong with the deployer because I tried it with Postman as well with the same result

**Comment by pfefferf** [comment]
@silkearians I do not see what the deployer should add if there is nothing there on the client :-)

**Comment by silkearians** [comment]
As far as we could see the "types" folder with the issue is not the one under test/unit but on root - this types folder seems to contain XmlType.js as well as XmlType-dbg.js (XmlType-dbg.js is not visible directly in UI5 ABAP repo based on BSP repo with teh file name as it contains "-" and therefore file name is converted to hash-like name, see path mapping in XML UI5RepositoryPathMapping.xml).
What is currently not clear for us is why the OData service thinks it should delete "types" folder if there are still the files XmlType.js and XmlType-dbg.js inside ...
We have asked the customer in the ticket he raised to SAP to send us the complete project so that we can reproduce and further analyze.
We will share the results then.

**Comment by silkearians** [comment]
We found an issue in the ABAP coding which is fixed with [Note 3089702](https://launchpad.support.sap.com/#/notes/3089702). Therefore I am closing this issue here.

**Comment by treee111** [comment]
Hi @silkearians, thanks for providing the note. 👍 
We had the same issue and it got resolved after implementing the note.
