### ISSUE TITLE
[1.x branch] No error is thrown when transport is already released

### ISSUE THREAD

**Issue by mjochemsen** [pfefferf/ui5-nwabap-deployer#57]
In older versions there was an error stating something like this when trying to deploy under a transport that is already released:
"Request XYZ is already released."

It looks like the latest commit in the 1.x.x branch resolves this issue, but this is not yet available in the 1.0.7 branch on NPM:
https://www.npmjs.com/package/grunt-nwabap-ui5uploader?activeTab=versions

Unfortunately, our corporate firewall doesn't allow us to install directly from Github. Is it possible that the 1.x version on the NPM repository needs an update?

Thanks a ton!

**Comment by pfefferf** [comment]
What code position do you mean in detail?

**Comment by mjochemsen** [comment]
Thank you for the quick reply.

I meant that yesterday the latest version on the 1.x.x branch that was available on NPM was > 1 year old:
https://www.npmjs.com/package/grunt-nwabap-ui5uploader?activeTab=versions

That version did thus not yet have the latest fixes, such as those in commit 198bcd2.

They seem to have been updated now, as the issue I was experiencing with V1.x.x is now resolved with the latest version from NPM. Thanks a lot for your help!
