### ISSUE TITLE
Parse Error: Header overflow

### ISSUE THREAD

**Issue by Fjaoos** [pfefferf/ui5-nwabap-deployer#59]
Hi,

I have found a strange error when I try to deploy an application for the **first time** to a system.
This happens on a jenkins server running in AWS cloud. I cannot reproduce it on my local machine. If I hit replay on the jenkins build, it works just fine.
Version 2.1.0
This is the error: 
![image](https://user-images.githubusercontent.com/19299859/145232628-c6d55018-f34c-4988-bf42-553f78236f8d.png)

This the full verbose log:
+ /home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/@ui5/cli/bin/ui5.js build --include-task=generateManifestBundle generateCachebusterInfo '--exclude-task=*' --include-task=uploadCOS --verbose
verb cli:middlewares:base using @ui5/cli version 2.14.1 (from /home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/@ui5/cli/bin/ui5.js)
verb cli:middlewares:base using node version v12.22.1
verb normalizer:normalizer Building dependency tree...
verb normalizer:translators:npm Analyzing yyi00862bheft (/home/ec2-user/workspace/UI5-Build-and-Deploy) (dependency of nothing - root project)
verb normalizer:translators:npm Ignoring npm dependency @ui5/cli. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma-chrome-launcher. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma-mocha-reporter. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma-qunit. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma-sinon. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency karma-ui5. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency qunit. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency sinon. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Analyzing ui5-task-nwabap-deployer (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ui5-task-nwabap-deployer) (dependency of yyi00862bheft)
verb normalizer:translators:npm Analyzing ui5-middleware-simpleproxy (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ui5-middleware-simpleproxy) (dependency of yyi00862bheft)
verb normalizer:translators:npm Ignoring npm dependency @ui5/logger. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency dotenv. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency express-http-proxy. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Ignoring npm dependency minimatch. Not defined in UI5-dependency configuration.
verb normalizer:translators:npm Analyzing ui5-nwabap-deployer-core (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ui5-nwabap-deployer-core) (dependency of ui5-task-nwabap-deployer)
verb normalizer:translators:npm Analyzing dotenv (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ui5-task-nwabap-deployer/node_modules/dotenv) (dependency of ui5-task-nwabap-deployer)
verb normalizer:translators:npm Analyzing @ui5/logger (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/@ui5/logger) (dependency of ui5-task-nwabap-deployer)
verb normalizer:translators:npm Analyzing axios (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/axios) (dependency of ui5-nwabap-deployer-core)
verb normalizer:translators:npm Analyzing retry-axios (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/retry-axios) (dependency of ui5-nwabap-deployer-core)
verb normalizer:translators:npm Analyzing xmldoc (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/xmldoc) (dependency of ui5-nwabap-deployer-core)
verb normalizer:translators:npm Analyzing yazl (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/yazl) (dependency of ui5-nwabap-deployer-core)
verb normalizer:translators:npm Analyzing npmlog (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/npmlog) (dependency of @ui5/logger)
verb normalizer:translators:npm Analyzing follow-redirects (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/follow-redirects) (dependency of axios)
verb normalizer:translators:npm Analyzing sax (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/sax) (dependency of xmldoc)
verb normalizer:translators:npm Analyzing buffer-crc32 (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/buffer-crc32) (dependency of yazl)
verb normalizer:translators:npm Analyzing console-control-strings (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/console-control-strings) (dependency of npmlog)
verb normalizer:translators:npm Analyzing gauge (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/gauge) (dependency of npmlog)
verb normalizer:translators:npm Analyzing are-we-there-yet (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/are-we-there-yet) (dependency of npmlog)
verb normalizer:translators:npm Analyzing set-blocking (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/set-blocking) (dependency of npmlog)
verb normalizer:translators:npm Analyzing console-control-strings (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/console-control-strings) (dependency of gauge)
verb normalizer:translators:npm Analyzing aproba (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/aproba) (dependency of gauge)
verb normalizer:translators:npm Analyzing has-unicode (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/has-unicode) (dependency of gauge)
verb normalizer:translators:npm Analyzing object-assign (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/object-assign) (dependency of gauge)
verb normalizer:translators:npm Analyzing signal-exit (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/signal-exit) (dependency of gauge)
verb normalizer:translators:npm Analyzing string-width (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/string-width) (dependency of gauge)
verb normalizer:translators:npm Analyzing strip-ansi (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/strip-ansi) (dependency of gauge)
verb normalizer:translators:npm Analyzing wide-align (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/wide-align) (dependency of gauge)
verb normalizer:translators:npm Analyzing delegates (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/delegates) (dependency of are-we-there-yet)
verb normalizer:translators:npm Analyzing readable-stream (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/readable-stream) (dependency of are-we-there-yet)
verb normalizer:translators:npm Analyzing strip-ansi (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/strip-ansi) (dependency of string-width)
verb normalizer:translators:npm Analyzing string-width (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/string-width) (dependency of wide-align)
verb normalizer:translators:npm Analyzing code-point-at (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/code-point-at) (dependency of string-width)
verb normalizer:translators:npm Analyzing is-fullwidth-code-point (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/is-fullwidth-code-point) (dependency of string-width)
verb normalizer:translators:npm Analyzing ansi-regex (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ansi-regex) (dependency of strip-ansi)
verb normalizer:translators:npm Analyzing core-util-is (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/core-util-is) (dependency of readable-stream)
verb normalizer:translators:npm Analyzing inherits (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/inherits) (dependency of readable-stream)
verb normalizer:translators:npm Analyzing isarray (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/isarray) (dependency of readable-stream)
verb normalizer:translators:npm Analyzing process-nextick-args (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/process-nextick-args) (dependency of readable-stream)
verb normalizer:translators:npm Analyzing safe-buffer (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/safe-buffer) (dependency of readable-stream)
verb normalizer:translators:npm Analyzing string_decoder (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/string_decoder) (dependency of readable-stream)
verb normalizer:translators:npm Analyzing util-deprecate (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/util-deprecate) (dependency of readable-stream)
verb normalizer:translators:npm Analyzing ansi-regex (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ansi-regex) (dependency of strip-ansi)
verb normalizer:translators:npm Analyzing code-point-at (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/code-point-at) (dependency of string-width)
verb normalizer:translators:npm Analyzing is-fullwidth-code-point (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/is-fullwidth-code-point) (dependency of string-width)
verb normalizer:translators:npm Analyzing strip-ansi (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/strip-ansi) (dependency of string-width)
verb normalizer:translators:npm Analyzing safe-buffer (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/safe-buffer) (dependency of string_decoder)
verb normalizer:translators:npm Analyzing number-is-nan (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/number-is-nan) (dependency of is-fullwidth-code-point)
verb normalizer:translators:npm Analyzing number-is-nan (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/number-is-nan) (dependency of is-fullwidth-code-point)
verb normalizer:translators:npm Analyzing ansi-regex (/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ansi-regex) (dependency of strip-ansi)
verb normalizer:translators:npm [PERF] Consider defining UI5-dependencies in the package.json files of the relevant modules from the following list to improve npm translator execution time: ui5-task-nwabap-deployer, ui5-nwabap-deployer-core, dotenv, @ui5/logger, axios, retry-axios, xmldoc, yazl, npmlog, follow-redirects, sax, buffer-crc32, console-control-strings, gauge, are-we-there-yet, set-blocking, console-control-strings, aproba, has-unicode, object-assign, signal-exit, string-width, strip-ansi, wide-align, delegates, readable-stream, strip-ansi, string-width, code-point-at, is-fullwidth-code-point, ansi-regex, core-util-is, inherits, isarray, process-nextick-args, safe-buffer, string_decoder, util-deprecate, ansi-regex, code-point-at, is-fullwidth-code-point, strip-ansi, safe-buffer, number-is-nan, number-is-nan, ansi-regex
verb normalizer:translators:npm Treetop:
verb normalizer:translators:npm {
verb normalizer:translators:npm   id: 'yyi00862bheft',
verb normalizer:translators:npm   version: '0.0.1',
verb normalizer:translators:npm   path: '/home/ec2-user/workspace/UI5-Build-and-Deploy',
verb normalizer:translators:npm   dependencies: [
verb normalizer:translators:npm     {
verb normalizer:translators:npm       id: 'ui5-task-nwabap-deployer',
verb normalizer:translators:npm       version: '2.1.0',
verb normalizer:translators:npm       path: '/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ui5-task-nwabap-deployer',
verb normalizer:translators:npm       dependencies: [Array]
verb normalizer:translators:npm     },
verb normalizer:translators:npm     {
verb normalizer:translators:npm       id: 'ui5-middleware-simpleproxy',
verb normalizer:translators:npm       version: '0.7.5',
verb normalizer:translators:npm       path: '/home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ui5-middleware-simpleproxy',
verb normalizer:translators:npm       dependencies: []
verb normalizer:translators:npm     }
verb normalizer:translators:npm   ]
verb normalizer:translators:npm }
verb normalizer:projectPreprocessor Processing project yyi00862bheft on level 0...
verb normalizer:projectPreprocessor Processing dependency lookahead for yyi00862bheft: ui5-task-nwabap-deployer
verb normalizer:projectPreprocessor Processing dependency lookahead for yyi00862bheft: ui5-middleware-simpleproxy
verb normalizer:projectPreprocessor Applying extension ui5-task-nwabap-deployer...
verb normalizer:projectPreprocessor Applying extension ui5-middleware-simpleproxy...
verb normalizer:projectPreprocessor Applying extension uploadCOS...
verb types:application:ApplicationFormatter Formatting application project yyi00862bheft...
verb types:application:ApplicationFormatter Namespace of project yyi00862bheft is yyi00862_test_bheft (from manifest.json)
verb normalizer:projectPreprocessor Processed 3 projects in 268 ms
info builder:builder Building project yyi00862bheft not including dependencies...
verb builder:builder Building to ./dist...
info builder:builder 🛠  (1/1) Building project yyi00862bheft
verb resources:resourceFactory Prefixing virtual base path / of project yyi00862bheft /resources/yyi00862_test_bheft...
verb resources:resourceFactory New virtual base path: /resources/yyi00862_test_bheft/
info builder:builder application yyi00862bheft 🔨 (1/3) Running task generateManifestBundle...
verb resources:tracing:Trace:globs [Trace: /resources/yyi00862_test_bheft/**/{manifest.json,*.properties}
verb resources:tracing:Trace:globs   21 ms elapsed time 
verb resources:tracing:Trace:globs   1 glob executions
verb resources:tracing:Trace:globs   2 reader-collections involed:
verb resources:tracing:Trace:globs       1x source of yyi00862bheft
verb resources:tracing:Trace:globs       1x yyi00862bheft
verb resources:tracing:Trace:globs ======================]
verb resources:adapters:Memory Writing to virtual path /resources/yyi00862_test_bheft/manifest-bundle.zip
info builder:builder application yyi00862bheft 🔨 (2/3) Running task uploadCOS...
info builder:customtask:nwabap-deployer Start deploying UI5 sources.
verb resources:tracing:Trace:globs [Trace: **/*.*
verb resources:tracing:Trace:globs   8.66 ms elapsed time 
verb resources:tracing:Trace:globs   1 glob executions
verb resources:tracing:Trace:globs   2 reader-collections involed:
verb resources:tracing:Trace:globs       1x source of yyi00862bheft
verb resources:tracing:Trace:globs       1x yyi00862bheft
verb resources:tracing:Trace:globs ======================]
verb resources:tracing:total ==========================
verb resources:tracing:total [=> TRACE SUMMARY:
verb resources:tracing:total   44 ms elapsed time 
verb resources:tracing:total   2 trace calls 
verb resources:tracing:total   2 glob executions
verb resources:tracing:total   2 rl-collections involed:
verb resources:tracing:total       2x source of yyi00862bheft
verb resources:tracing:total       2x yyi00862bheft
verb resources:tracing:total ======================]
ERR! builder:customtask:nwabap-deployer Parse Error: Header overflow
ERR! builder:builder Build failed in 14 s
info builder:builder Executing cleanup tasks...

⚠️  Process Failed With Error

Error Message:
Parse Error: Header overflow

Stack Trace:
Error: Parse Error: Header overflow
    at /home/ec2-user/workspace/UI5-Build-and-Deploy/node_modules/ui5-task-nwabap-deployer/lib/ui5-task-nwabap-deployer.js:126:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

If you think this is an issue of the UI5 Tooling, you might report it using the following URL: https://github.com/SAP/ui5-tooling/issues/new/choose
[Pipeline] echo
Fehler beim Test-Deploy des Tasks: uploadCOS

Best Regards
fjaoos

**Comment by pfefferf** [comment]
not reproducable on my side
